/**
 * pi 的审批闸（#198）：pi 自己没有审批通道，ama 以 `-e <文件>` 给这一次运行加载一个最小扩展，
 * 把只读内置工具以外的每次工具调用经 RPC 的扩展对话框（`extension_ui_request{method: confirm}`）
 * 交给 ama——ama 再按模式决定直接拒绝、直接放行（auto-edit 下的文件编辑）或交给人。
 *
 * 扩展文件写在每个会话自己的临时目录（`mkdtemp`，只有当前用户可写），会话关闭时删除；
 * 不写 pi 的配置目录，不改用户的扩展设置。
 */

import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** 对话框标题：ama 只认这个标题的 confirm，其它扩展的对话框一律取消（不代答）。 */
export const PI_GATE_TITLE = "ama-approval";

/** pi 不经审批就放行的内置只读工具（也用于只读模式的 `--tools`）。 */
export const PI_READ_ONLY_TOOLS: readonly string[] = ["read", "grep", "find", "ls"];

/** 扩展源码（pi 用 jiti 加载 TypeScript；这里只用纯 JS 语法）。 */
export const PI_GATE_SOURCE = `// Generated by ama for one pi run: routes non-read-only tool calls to ama for approval.
const READ_ONLY = new Set(${JSON.stringify(PI_READ_ONLY_TOOLS)});
export default function (pi) {
  pi.on("tool_call", async (event, ctx) => {
    if (READ_ONLY.has(event.toolName)) return undefined;
    const ok = await ctx.ui.confirm(
      ${JSON.stringify(PI_GATE_TITLE)},
      JSON.stringify({ id: event.toolCallId, tool: event.toolName, input: event.input }),
    );
    return ok ? undefined : { block: true, reason: event.toolName + " was not approved by the user" };
  });
}
`;

/** 写一份闸扩展，返回路径与清理函数。 */
export function writePiGate(): { path: string; dispose(): void } {
  const dir = mkdtempSync(join(tmpdir(), "ama-pi-"));
  const path = join(dir, "ama-approval-gate.ts");
  writeFileSync(path, PI_GATE_SOURCE, { mode: 0o600 });
  return {
    path,
    dispose: () => rmSync(dir, { recursive: true, force: true }),
  };
}
